version: '3'
services:
  db:
    image: postgres:12.4-alpine
    container_name: postgres
    ports:
      - 5431:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: telegram_bot_daily
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    build: .
    container_name: telegram_bot_daily
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db